### ISSUE TITLE
Decoding from strings and bytestrings does not work

### ISSUE THREAD

**Issue by calpaterson** [flying-sheep/bcode#4]
BytesIO doesn't have a peek method.  I'm using the 1.0 version from PyPI.

``` python
(bcodeproblem)cal@curry:~/src$ python
Python 2.7.3 (default, Sep 26 2012, 21:51:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from bcoding import bencode, bdecode
>>> one = bdecode(b'i1e')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cal/src/bcodeproblem/local/lib/python2.7/site-packages/bcoding.py", line 118, in bdecode
    first_byte = f_or_data.peek(1)[:1]
AttributeError: '_io.BytesIO' object has no attribute 'peek'
>>> two = bdecode('3:two')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cal/src/bcodeproblem/local/lib/python2.7/site-packages/bcoding.py", line 118, in bdecode
    first_byte = f_or_data.peek(1)[:1]
AttributeError: '_io.BytesIO' object has no attribute 'peek'
```

**Comment by flying-sheep** [comment]
oh, you try it in python 2. i wonder how you even imported it with an non-ascii character in the source code ;)

but the bug is fixed; shoulda used unit tests :/

**Comment by calpaterson** [comment]
Thanks :)

**Comment by flying-sheep** [comment]
thank you! that was a pretty severe bug.
